INSERT INTO "authors" VALUES(1,'František Vomáčka');
INSERT INTO "authors" VALUES(2,'John Doe');
INSERT INTO "authors" VALUES(3,'Jan Novák');

INSERT INTO "articles" VALUES(1,'Rodičovské problémy Táty Singletonovského objektu','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed scelerisque, ligula ac rhoncus consequat, quam eros bibendum nunc, vitae egestas sem nulla vel enim. Ut id euismod velit. Nullam nec faucibus arcu. Maecenas faucibus pulvinar venenatis. Mauris commodo adipiscing lectus sit amet viverra. Aliquam porta nisi vitae eros tempus non fermentum augue varius. Cras libero diam, condimentum quis rutrum quis, imperdiet nec mi. Quisque laoreet, augue eu venenatis tristique, tellus lectus fermentum nisl, at pretium purus augue at risus. Nulla sed fermentum ligula. Nulla ut libero velit, eu dignissim dui. Morbi lacus mi, bibendum vitae sodales vitae, blandit eu tellus. Morbi imperdiet semper quam, vitae tempor nulla fermentum rhoncus. Praesent ultricies imperdiet leo, nec facilisis ligula ornare in. Phasellus a sagittis nulla. Aenean hendrerit arcu leo, a elementum justo. Sed ipsum lacus, ullamcorper et mattis sit amet, luctus vulputate arcu. Suspendisse ut ligula non turpis pellentesque aliquam quis eu ante. ',3,'2009-12-01',4.3,'TRUE');
INSERT INTO "articles" VALUES(2,'Sdílej své obrázky jednoduše Ukáz.at','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed scelerisque, ligula ac rhoncus consequat, quam eros bibendum nunc, vitae egestas sem nulla vel enim. Ut id euismod velit. Nullam nec faucibus arcu. Maecenas faucibus pulvinar venenatis. Mauris commodo adipiscing lectus sit amet viverra. Aliquam porta nisi vitae eros tempus non fermentum augue varius. Cras libero diam, condimentum quis rutrum quis, imperdiet nec mi. Quisque laoreet, augue eu venenatis tristique, tellus lectus fermentum nisl, at pretium purus augue at risus. Nulla sed fermentum ligula. Nulla ut libero velit, eu dignissim dui. Morbi lacus mi, bibendum vitae sodales vitae, blandit eu tellus. Morbi imperdiet semper quam, vitae tempor nulla fermentum rhoncus. Praesent ultricies imperdiet leo, nec facilisis ligula ornare in. Phasellus a sagittis nulla. Aenean hendrerit arcu leo, a elementum justo. Sed ipsum lacus, ullamcorper et mattis sit amet, luctus vulputate arcu. Suspendisse ut ligula non turpis pellentesque aliquam quis eu ante. ',2,'2010-01-31',0,'FALSE');
INSERT INTO "articles" VALUES(3,'NellaCMS - Comming Soon','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed scelerisque, ligula ac rhoncus consequat, quam eros bibendum nunc, vitae egestas sem nulla vel enim. Ut id euismod velit. Nullam nec faucibus arcu. Maecenas faucibus pulvinar venenatis. Mauris commodo adipiscing lectus sit amet viverra. Aliquam porta nisi vitae eros tempus non fermentum augue varius. Cras libero diam, condimentum quis rutrum quis, imperdiet nec mi. Quisque laoreet, augue eu venenatis tristique, tellus lectus fermentum nisl, at pretium purus augue at risus. Nulla sed fermentum ligula. Nulla ut libero velit, eu dignissim dui. Morbi lacus mi, bibendum vitae sodales vitae, blandit eu tellus. Morbi imperdiet semper quam, vitae tempor nulla fermentum rhoncus. Praesent ultricies imperdiet leo, nec facilisis ligula ornare in. Phasellus a sagittis nulla. Aenean hendrerit arcu leo, a elementum justo. Sed ipsum lacus, ullamcorper et mattis sit amet, luctus vulputate arcu. Suspendisse ut ligula non turpis pellentesque aliquam quis eu ante. ',2,'2010-02-22',63.5,'TRUE');
INSERT INTO "articles" VALUES(4,'Novinky na Ukáz.at','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed scelerisque, ligula ac rhoncus consequat, quam eros bibendum nunc, vitae egestas sem nulla vel enim. Ut id euismod velit. Nullam nec faucibus arcu. Maecenas faucibus pulvinar venenatis. Mauris commodo adipiscing lectus sit amet viverra. Aliquam porta nisi vitae eros tempus non fermentum augue varius. Cras libero diam, condimentum quis rutrum quis, imperdiet nec mi. Quisque laoreet, augue eu venenatis tristique, tellus lectus fermentum nisl, at pretium purus augue at risus. Nulla sed fermentum ligula. Nulla ut libero velit, eu dignissim dui. Morbi lacus mi, bibendum vitae sodales vitae, blandit eu tellus. Morbi imperdiet semper quam, vitae tempor nulla fermentum rhoncus. Praesent ultricies imperdiet leo, nec facilisis ligula ornare in. Phasellus a sagittis nulla. Aenean hendrerit arcu leo, a elementum justo. Sed ipsum lacus, ullamcorper et mattis sit amet, luctus vulputate arcu. Suspendisse ut ligula non turpis pellentesque aliquam quis eu ante. ',1,'2010-03-01',5.1,'FALSE');
INSERT INTO "articles" VALUES(5,'PHP vs. Ruby','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed scelerisque, ligula ac rhoncus consequat, quam eros bibendum nunc, vitae egestas sem nulla vel enim. Ut id euismod velit. Nullam nec faucibus arcu. Maecenas faucibus pulvinar venenatis. Mauris commodo adipiscing lectus sit amet viverra. Aliquam porta nisi vitae eros tempus non fermentum augue varius. Cras libero diam, condimentum quis rutrum quis, imperdiet nec mi. Quisque laoreet, augue eu venenatis tristique, tellus lectus fermentum nisl, at pretium purus augue at risus. Nulla sed fermentum ligula. Nulla ut libero velit, eu dignissim dui. Morbi lacus mi, bibendum vitae sodales vitae, blandit eu tellus. Morbi imperdiet semper quam, vitae tempor nulla fermentum rhoncus. Praesent ultricies imperdiet leo, nec facilisis ligula ornare in. Phasellus a sagittis nulla. Aenean hendrerit arcu leo, a elementum justo. Sed ipsum lacus, ullamcorper et mattis sit amet, luctus vulputate arcu. Suspendisse ut ligula non turpis pellentesque aliquam quis eu ante. ',1,'2010-01-15',91,'FALSE');
INSERT INTO "articles" VALUES(6,'HipHop for PHP','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed scelerisque, ligula ac rhoncus consequat, quam eros bibendum nunc, vitae egestas sem nulla vel enim. Ut id euismod velit. Nullam nec faucibus arcu. Maecenas faucibus pulvinar venenatis. Mauris commodo adipiscing lectus sit amet viverra. Aliquam porta nisi vitae eros tempus non fermentum augue varius. Cras libero diam, condimentum quis rutrum quis, imperdiet nec mi. Quisque laoreet, augue eu venenatis tristique, tellus lectus fermentum nisl, at pretium purus augue at risus. Nulla sed fermentum ligula. Nulla ut libero velit, eu dignissim dui. Morbi lacus mi, bibendum vitae sodales vitae, blandit eu tellus. Morbi imperdiet semper quam, vitae tempor nulla fermentum rhoncus. Praesent ultricies imperdiet leo, nec facilisis ligula ornare in. Phasellus a sagittis nulla. Aenean hendrerit arcu leo, a elementum justo. Sed ipsum lacus, ullamcorper et mattis sit amet, luctus vulputate arcu. Suspendisse ut ligula non turpis pellentesque aliquam quis eu ante. ',3,'2010-02-28',0.1,'TRUE');
INSERT INTO "articles" VALUES(7,'ScreenCast - IIS7.5 + PHP5.3 + MySQL + Nette Framework','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed scelerisque, ligula ac rhoncus consequat, quam eros bibendum nunc, vitae egestas sem nulla vel enim. Ut id euismod velit. Nullam nec faucibus arcu. Maecenas faucibus pulvinar venenatis. Mauris commodo adipiscing lectus sit amet viverra. Aliquam porta nisi vitae eros tempus non fermentum augue varius. Cras libero diam, condimentum quis rutrum quis, imperdiet nec mi. Quisque laoreet, augue eu venenatis tristique, tellus lectus fermentum nisl, at pretium purus augue at risus. Nulla sed fermentum ligula. Nulla ut libero velit, eu dignissim dui. Morbi lacus mi, bibendum vitae sodales vitae, blandit eu tellus. Morbi imperdiet semper quam, vitae tempor nulla fermentum rhoncus. Praesent ultricies imperdiet leo, nec facilisis ligula ornare in. Phasellus a sagittis nulla. Aenean hendrerit arcu leo, a elementum justo. Sed ipsum lacus, ullamcorper et mattis sit amet, luctus vulputate arcu. Suspendisse ut ligula non turpis pellentesque aliquam quis eu ante. ',3,'2010-04-06',97586.3,'TRUE');
INSERT INTO "articles" VALUES(8,'ScreenCast - PEAR + PHPUnit','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed scelerisque, ligula ac rhoncus consequat, quam eros bibendum nunc, vitae egestas sem nulla vel enim. Ut id euismod velit. Nullam nec faucibus arcu. Maecenas faucibus pulvinar venenatis. Mauris commodo adipiscing lectus sit amet viverra. Aliquam porta nisi vitae eros tempus non fermentum augue varius. Cras libero diam, condimentum quis rutrum quis, imperdiet nec mi. Quisque laoreet, augue eu venenatis tristique, tellus lectus fermentum nisl, at pretium purus augue at risus. Nulla sed fermentum ligula. Nulla ut libero velit, eu dignissim dui. Morbi lacus mi, bibendum vitae sodales vitae, blandit eu tellus. Morbi imperdiet semper quam, vitae tempor nulla fermentum rhoncus. Praesent ultricies imperdiet leo, nec facilisis ligula ornare in. Phasellus a sagittis nulla. Aenean hendrerit arcu leo, a elementum justo. Sed ipsum lacus, ullamcorper et mattis sit amet, luctus vulputate arcu. Suspendisse ut ligula non turpis pellentesque aliquam quis eu ante. ',3,'2010-03-25',1.11,'FALSE');
INSERT INTO "articles" VALUES(9,'Slabiny Nette Frameworku','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed scelerisque, ligula ac rhoncus consequat, quam eros bibendum nunc, vitae egestas sem nulla vel enim. Ut id euismod velit. Nullam nec faucibus arcu. Maecenas faucibus pulvinar venenatis. Mauris commodo adipiscing lectus sit amet viverra. Aliquam porta nisi vitae eros tempus non fermentum augue varius. Cras libero diam, condimentum quis rutrum quis, imperdiet nec mi. Quisque laoreet, augue eu venenatis tristique, tellus lectus fermentum nisl, at pretium purus augue at risus. Nulla sed fermentum ligula. Nulla ut libero velit, eu dignissim dui. Morbi lacus mi, bibendum vitae sodales vitae, blandit eu tellus. Morbi imperdiet semper quam, vitae tempor nulla fermentum rhoncus. Praesent ultricies imperdiet leo, nec facilisis ligula ornare in. Phasellus a sagittis nulla. Aenean hendrerit arcu leo, a elementum justo. Sed ipsum lacus, ullamcorper et mattis sit amet, luctus vulputate arcu. Suspendisse ut ligula non turpis pellentesque aliquam quis eu ante. ',1,'2010-04-11',5988209.2,'TRUE');
INSERT INTO "articles" VALUES(10,'ActiveMapper ORM pro Nette Framework','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed scelerisque, ligula ac rhoncus consequat, quam eros bibendum nunc, vitae egestas sem nulla vel enim. Ut id euismod velit. Nullam nec faucibus arcu. Maecenas faucibus pulvinar venenatis. Mauris commodo adipiscing lectus sit amet viverra. Aliquam porta nisi vitae eros tempus non fermentum augue varius. Cras libero diam, condimentum quis rutrum quis, imperdiet nec mi. Quisque laoreet, augue eu venenatis tristique, tellus lectus fermentum nisl, at pretium purus augue at risus. Nulla sed fermentum ligula. Nulla ut libero velit, eu dignissim dui. Morbi lacus mi, bibendum vitae sodales vitae, blandit eu tellus. Morbi imperdiet semper quam, vitae tempor nulla fermentum rhoncus. Praesent ultricies imperdiet leo, nec facilisis ligula ornare in. Phasellus a sagittis nulla. Aenean hendrerit arcu leo, a elementum justo. Sed ipsum lacus, ullamcorper et mattis sit amet, luctus vulputate arcu. Suspendisse ut ligula non turpis pellentesque aliquam quis eu ante. ',2,'2010-04-30','3.14','FALSE');

INSERT INTO "profiles" VALUES(1,'http://www.example.com');
INSERT INTO "profiles" VALUES(3,'http://www.test.com');

INSERT INTO "tags" VALUES(1,'PHP');
INSERT INTO "tags" VALUES(2,'Nette');
INSERT INTO "tags" VALUES(3,'dibi');
INSERT INTO "tags" VALUES(4,'Nella');
INSERT INTO "tags" VALUES(5,'PEAR');
INSERT INTO "tags" VALUES(6,'PHPUnit');
INSERT INTO "tags" VALUES(7,'Windows');
INSERT INTO "tags" VALUES(8,'Ruby');
INSERT INTO "tags" VALUES(9,'MySQL');
INSERT INTO "tags" VALUES(10,'IIS');
INSERT INTO "tags" VALUES(11,'hiPHoP');
INSERT INTO "tags" VALUES(12,'facebook');
INSERT INTO "tags" VALUES(13,'ukáz.at');
INSERT INTO "tags" VALUES(14,'hosting');
INSERT INTO "tags" VALUES(15,'ORM');
INSERT INTO "tags" VALUES(16,'ActiveMapper');
INSERT INTO "tags" VALUES(17,'Singleton');
INSERT INTO "tags" VALUES(18,'Late Static Binding');

INSERT INTO "articles_tags" VALUES(1,18);
INSERT INTO "articles_tags" VALUES(1,17);
INSERT INTO "articles_tags" VALUES(1,1);
INSERT INTO "articles_tags" VALUES(2,2);
INSERT INTO "articles_tags" VALUES(2,1);
INSERT INTO "articles_tags" VALUES(2,13);
INSERT INTO "articles_tags" VALUES(3,4);
INSERT INTO "articles_tags" VALUES(3,2);
INSERT INTO "articles_tags" VALUES(3,3);
INSERT INTO "articles_tags" VALUES(4,1);
INSERT INTO "articles_tags" VALUES(4,13);
INSERT INTO "articles_tags" VALUES(4,2);
INSERT INTO "articles_tags" VALUES(5,1);
INSERT INTO "articles_tags" VALUES(5,8);
INSERT INTO "articles_tags" VALUES(6,1);
INSERT INTO "articles_tags" VALUES(6,12);
INSERT INTO "articles_tags" VALUES(6,11);
INSERT INTO "articles_tags" VALUES(7,10);
INSERT INTO "articles_tags" VALUES(7,2);
INSERT INTO "articles_tags" VALUES(7,9);
INSERT INTO "articles_tags" VALUES(7,1);
INSERT INTO "articles_tags" VALUES(7,7);
INSERT INTO "articles_tags" VALUES(8,5);
INSERT INTO "articles_tags" VALUES(8,6);
INSERT INTO "articles_tags" VALUES(8,7);
INSERT INTO "articles_tags" VALUES(8,1);
INSERT INTO "articles_tags" VALUES(9,1);
INSERT INTO "articles_tags" VALUES(9,2);
INSERT INTO "articles_tags" VALUES(10,16);
INSERT INTO "articles_tags" VALUES(10,2);
INSERT INTO "articles_tags" VALUES(10,3);
INSERT INTO "articles_tags" VALUES(10,1);